# Abstract
+ Project title: Convert Kevin Dowd's Matlab code
+ Project idea page: https://github.com/rstats-gsoc/gsoc2015/wiki/Convert-Dowd%27s-Code

"Measuring Market Risk" is a widely used book covering important topics in risk 
measurement, also providing matlab code of modern quantitative finance algorithms. 
Recently, most of the code for financial algorithms provided either on the VBA or on 
Matlab, which increases the barrier to entry. 

In my opinion, R is much more friendly environment for learning and experimentation,
that does not require too much at the start, but at the same time able to cover your needs
with an increase in the level of your professionalism.

I hope this project will be a solid move towards widely accessible modern risk measure
techniques.

# Content

## Personal Details
+ Egorov Evgenii
+ Melange username: egorovevgenii
+ email: e.evgenovich@gmail.com
+ phone: +7(909)997-44-97
+ postal address: Russia, 630105, Novosibirsk, Kavaleryska 2 108

## Project Proposal
I have read the parts of the book "Dowd, K. Measuring Market Risk" related to the code. 
I have studied source matlab code, which was provided with the book, and played with it a 
bit in matlab. Also, I have written R functions and and documented them, relating Dowd's 
code 'Copula functions' for estimation VaR with gaussian copula. 
For easy test it, I made package, which you can find in 
https://github.com/evgeniiegorov/VaRgcop

I propose to сonvert Kevin Dowd's Matlab code from 'Measuring Market Risk'. 
Not mechanically, but optimizing and using features of R and more sophisticated numerical
algorithms.

Also, I propose to make some extensions of functional. For example, it isn't big step to 
go from gaussian-copula-VaR for 2 assets portfolio to n assets portfolio. But, in my 
opinion, it will be a big difference in functionality for those, who use the package. 

## Coding plan & methods

Literature: 

For quantative finance algotrithms field:
+ Dowd, K. (2005) Measuring Market Risk
+ A.McNeil, R.Frey, P.Embrechts "Quantitative Risk Management: Concepts,Techniques&Tools"

For numerical methods:
+ R. W. Hamming, "Numerical Methods for Scientists and Engineers"
+ S.A. Teukolsky, W.T. Vetterling, B.P. Flannery  "Numerical Recipes 3rd Edition: 
The Art of Scientific Computing"
 
As code style I will follow:
+ http://adv-r.had.co.nz/Style.html (also as R table-book)
+ http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml

Kevin Dowd's Matlab code is divided into sections. Within each section, I will show the
functionality that will be implemented. And explain the reasons for which some functions
will be not implemented. (if no comments ==> will be implemented in project)

+ Backtest
  + Binomial backtest --> Value-at-Risk backtesting 
	+ Blancoihle backtest -->  Value-at-Risk backtesting
	+ Cristoffersen backtest -->  Value-at-Risk backtesting
	+ Lopez backtest -->  Value-at-Risk backtesting	
	+ Jarquebere --> distribution normality test --> fBasics
	+ KS test --> distribution equality test --> fBasics
	+ Kuiper test --> distribution equality test --> CircStats
	+ AD test --> distribution equality test --> nortest
Thus, I don't see the need of Jarquebre and KS test implementation, package fBasics is 
widely used. Another story about Kuiper and AD test, it is not convenient to install many 
packages for a single function. So we need to implement them. Also as all Value-at-Risk 
backtesting functions.

+ Bootstrap 
	+ bootstrap estimation of VaR and ES, condifence interval
	+ plots: bootstrap ES, VaR

+ Copula function
	+ gaussian, product, gumbel copula VaR for portfolio with two assets
	!! My extension: modify copulas to n-assets portfolio
	 
+ Cornish-Fisher functions
	+ compute ES,VaR using Corner-Fisher adjustment  --> PerformanceAnalytics
This functions are already in PerformanceAnalytics package. :)
	
+ Exploratory data plots
	+ hill plot, mef plot, Pickands plot
	+ normalqqplot, tqqplot --> stats
Hence, we need to implement only hill plot, mef plot anf Pickands plot.

+ Frechet/Generalised Pareto/Gumbel functions 
	  Assuming extreme losses are Frechet/Generalised Pareto/Gumbel distributed
	+ estimate VaR, ES 
	+ plot: VaR-confidence level, ES-confidence level
Here I will naturally combined and parameterized function of VaR,ES estimate and plot, 
with respect to how are extreme losses distributed.

+ Kernel functions
	+ Estimate VaR, ES with variety of kernels: box, epanchikov, normal, triangle

+ Options functions
	+ ES, VaR estimation to american put option by binomial tree, Monte-Carlo simulation
	+ ES of BS call, put via Monte-Carlo simulation
	+ Price of BS call,put via closed solution
	+ VaR of long, short postion in BS call,put closed solution
	!! My extension: option pricing with stochastic volatility 

+ Log-t/Lognormal functions 
	  Assuming geometric returns are t/normally distributed:
	+ estimate ES/VaR
	+ percentiles of ES/VaR distribution
	+ plot: ES/VaR-confidence level, ES/VaR-holding period, 
	  ES/VaR-holding period-confidence level
Also here I will naturally combined and parameterized functions with respect to how are 
geometric returns distributed.

+ Principal components functions
	+ estimates and plot ES, VaR by principal component analysis
	
+ Miscellaneous functions
	+ estimates VaR, ES of a coupon paying bond via monte-carlo
	+ estimates VaR, ES of portfolio, assuming loss dataset is transformed using Box-Cox
	
+ t-risk functions 
	+ estimates VaR/ES assuming P/L is t-distributed, for given 
	confidence level and holding period
	+ Estimates percentiles of VaR/ES distribution function
	+ plot: VaR/ES-confidence level, VaR/ES-holding period, 
	VaR/ES-confidence level-holding period 	

+ Historical simulation functions --> PerformanceAnalytics
+ Normal functions --> PerformanceAnalytics
This functions are already in PerformanceAnalytics package. :)


## Management of coding & timeline

I'm plannig to work ~ 40 hours in week in the GSoC period to this project. 
On the other hand, my goal is not to work 40 hours in week, but to reach all goals of 
the project. Hence, I'm certainly willing to try my best. Thus, I will have no other 
commitments during this summer. 

For transparency and for the benefit of the community, I'll be blogging my development,
include description of financial algorithms, code (and and why it is so) and tests. 

I plan to commit each week. About all deviations I will communicate immediately with 
mentors of the project. My planned schedule (atom of time is week, atom of week result
is section) is:

#### 27 April - 25 May
+ 1 Backtest, Bootstrap 
+ 2,3 Copula function 
+ 4 Exploratory data plots

#### 26 May - 26 June
+ 1 Frechet/Generalised Pareto/Gumbel functions
+ 2 Kernel functions 
+ 3,4 Options functions

#### 27 June - 2 Jule (Mid-term)
+ 1 documentation&testing what wasn't, provide examples

#### 3 Jule - 17 August
+ 1 Log-t/Lognormal functions 
+ 2 Principal components functions
+ 3 Miscellaneous functions
+ 4 t-risk functions 
+ 5 documentation&testing what wasn't, provide examples

#### 17 August - 20 August
+ all recheck, final :)

Note these are approximated schedule. Please allow minor adjustments (within 2 to 3 days)
according to the actual project status.

## Test task
I solved the problem of calculating the value-at-risk using a Gaussian copula for 
a portfolio of two assets, which P/L has normal distribution.
The task is divided into steps:
* Evaluation of the Gaussian copula on the it domain: unit cube
* Calculation of the distribution function return assets
* Finding value-under-risk as a quantile, for a given confidence level 

Then I write documentation with roxygen2 and build the package. 
You can find package, source code and example of using here:
https://github.com/evgeniiegorov/VaRgcop

Also in example I provide visualization of gaussian copula and it dependence of level
of correlation (with library 'manipulate')

## Academic Experience
I graduated with a B.S. degree in Economics from Moscow State University, Russia, in 2009.
My B.S. thesis was about option pricing with implementation in R. 
Now I am student of Moscow State University, finishing second year of master degree in
quantitate finance. 

Also I participate in Centre of Mathematical Finance MSU as instructor. 
I taught a group of students of Applied Econometrics, mostly on examples of how to measure
the risk of a financial portfolio based on coherent measures, step-by-step to more 
sophisticated cases. However, the main objective of the course was to introduce students 
to the language R and to refresh mathematical statistics skills for more advanced courses.
For more information about the centre and about my activities on slides 
http://www.slideshare.net/CMFMSU/20140913-cmf-fall-2014-presentation

## Work/Internship Experience
Also, I have industrial experience in credit risk estimating with R in top-10 Russian bank  
You can find review about my work in my LinkedIn https://www.linkedin.com/in/egorovevgenii

##  Mentors
+ Mentor names: Peter Carl, Brian Peterson
+ Mentor emails: peter@braverock.com, brian@braverock.com 
+ Mentor id in melage: peter_carl (I have emailed with him)

I emailed  Peter Carl and he gave me some useful tips. I realize the importance of
staying in touch with a mentor when working remotely and promise do it. 

## Why Rstats
It sounds a bit strange, but R has played a big role in my life, and my friends. 
Without it, and without a huge number of different packages, we were not able to create 
Centre for Mathematical Finance, as we would like. I will be very happy to contribute to 
the development of the package, so I'm sure that it can really help many people in their 
projects.

